language: php

sudo: false

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - curl --version
  - composer self-update
  - composer update --no-interaction --no-progress $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit -v

after_script:
  - php vendor/bin/coveralls -v

after_success:
  - if  [ $TRAVIS_PHP_VERSION = '7.1' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ] && [ $COMPOSER_FLAGS = '']; then sh bin/generate-api; fi
